[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "cryosbi"
authors = [
   { name = "David Silva-Sanchez", email = "david.silva@yale.edu"},
   { name = "Lars Dingeldein"},
   { name = "Pilar Cossio"},
   { name = "Roberto Covino"}
]


version = "0.2"
dependencies = [
    "zuko",
    "torch",
    "numpy",
    "matplotlib",
    "scipy",
    "torchvision",
    "mrcfile",
    "tqdm",
    "hydra-core>=1.3",
    "tensorboard>=2.14",
]


[project.scripts]
make_torch_models    = "cryo_sbi.utils.__main__:main"
classifier_inference = "cryo_sbi.inference.__main__:main"
train_classifier     = "cryo_sbi.training.__main__:main"
