# Training configuration with MLP classifier
embedding:
  model: RESNET18
  out_dim: 128

classifier:
  model: MLP
  num_classes: 44         # Must match number of models in model_file
  num_layers: 8
  nodes_per_layer: 128
  dropout: 0.05

learning_rate: 0.0005
one_cycle_scheduler: true
clip_gradient: 5.0
weight_decay: 0.001
batch_size: 128
